version: '3'
services:
  yardly:
    container_name: yardly
    build: .
    image: yardly:latest
    ports:
      - "8111:8111"
    volumes:
      - "/dev/bus/usb:/dev/bus/usb"
    devices:
      - "/dev/RFCAT1:/dev/RFCAT1"
    restart: always
